lecteurcarte.o: lecteurcarte.c lecteurcarte.h bool.h voyant.h
borne.o: borne.c lecteurcarte.h bool.h voyant.h base_clients.h timer.h
base_clients.o: base_clients.c base_clients.h bool.h voyant.h
boutton.o: boutton.c boutton.h voyant.h timer.h
voyant.o: voyant.c voyant.h timer.h
timer.o: timer.c timer.h
